[package]
name = "tsclientlib"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
description = "A library to create TeamSpeak clients and bots."
repository = "https://github.com/ReSpeak/tsclientlib"
readme = "README.md"
keywords = ["teamspeak3", "ts3", "voip"]
categories = ["multimedia"]
license = "OSL-3.0"
build = "build/build.rs"
edition = "2018"
include = [
	"/Cargo.toml",
	"/README.md",
	"**/*.rs",
	"/build/*.tt",
]

[package.metadata.docs.rs]
features = ["unstable"]

[features]
# Enable the unstable api
unstable = []

[dependencies]
anyhow = "1"
base64 = "0.12"
futures = "0.3"
git-testament = "0.1"
itertools = "0.9"
num-traits = "0.2"
pin-utils = "0.1.0-alpha.4"
rand = "0.7"
reqwest = "0.10"
slog = "2"
slog-async = "2"
slog-perf = "0.2"
slog-term = "2"
thiserror = "1"
time = "0.2"
tokio = { version = "0.2", features = ["stream", "time"] }
trust-dns-proto = "0.19"
trust-dns-resolver = "0.19"
ts-bookkeeping = { path = "../utils/ts-bookkeeping" }
tsproto = { path = "../tsproto", version = "=0.1.0" }
tsproto-packets = { path = "../utils/tsproto-packets" }

[build-dependencies]
heck = "0.3"
t4rust-derive = "0.2"
tsproto-structs = { path = "../utils/tsproto-structs", version = "=0.1.0" }

[dev-dependencies]
audiopus = "0.2"
sdl2 = "0.33"
structopt = { version = "0.3", default-features = false }
tokio = { version = "0.2", features = ["rt-threaded"] }
tokio-signal = "0.2"
