[package]
name = "tsclientlib"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
description = "A library to create TeamSpeak clients and bots."
repository = "https://github.com/ReSpeak/tsclientlib"
readme = "README.md"
keywords = ["teamspeak3", "ts3", "voip"]
categories = ["multimedia"]
license = "MIT/Apache-2.0"
build = "build/build.rs"
edition = "2018"
include = [
	"/Cargo.toml",
	"/README.md",
	"**/*.rs",
]

[features]
audio = ["tsproto-audio", "gstreamer"]

[dependencies]
base64 = "0.10"
bytes = "0.4"
chashmap = "2"
chrono = "0.4"
derive_more = "0.14"
failure = "0.1"
futures = "0.1"
gstreamer = { version = "0.11", optional = true }
itertools = "0.8"
parking_lot = "0.7"
rand = "0.6"
reqwest = "0.9"
slog = "2"
slog-async = "2"
slog-perf = "0.2"
slog-term = "2"
tokio = "0.1"
tokio-threadpool = "0.1"
trust-dns-proto = "0.7"
trust-dns-resolver = "0.10"
tsproto = { path = "../tsproto", version = "=0.1.0" }
tsproto-audio = { path = "../utils/tsproto-audio", version = "=0.1.0", optional = true }
tsproto-commands = { path = "../utils/tsproto-commands", version = "=0.1.0" }

[build-dependencies]
built = "0.3"
t4rust-derive = "0.1.3"
tsproto-structs = { path = "../utils/tsproto-structs", version = "=0.1.0" }

[dev-dependencies]
structopt = "0.2"
tokio-signal = "0.2"
