[package]
name = "tsclientlib"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
build = "build/build.rs"

[dependencies]
base64 = "0.9"
chrono = "0.4"
failure = "0.1"
futures = "0.1"
rand = "0.5"
reqwest = "0.8"
slog = "2"
slog-async = "2"
slog-perf = "0.2"
slog-term = "2"
tokio-core = "0.1"
trust-dns-proto = "0.5.0-alpha.1"
trust-dns-resolver = "0.10.0-alpha.2"
tsproto = { path = "../tsproto" }
tsproto-commands = { path = "../tsproto-commands" }

[build-dependencies]
tsproto-util = { path = "../tsproto-util" }

[dev-dependencies]
structopt = "0.2"
