[package]
name = "tsclientlib"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
description = "A library to create TeamSpeak clients and bots."
repository = "https://github.com/ReSpeak/tsclientlib"
readme = "README.md"
keywords = ["teamspeak3", "ts3", "voip"]
categories = ["multimedia"]
license = "OSL-3.0"
build = "build/build.rs"
edition = "2018"
include = [
	"/Cargo.toml",
	"/README.md",
	"**/*.rs",
	"/build/*.tt",
]

[dependencies]
base64 = "0.10"
bytes = "0.4"
chashmap = "2"
derive_more = "0.14"
failure = "0.1"
futures = "0.1"
git-testament = "0.1"
itertools = "0.8"
num-traits = "0.2"
parking_lot = "0.7"
rand = "0.6"
reqwest = "0.9"
slog = "2"
slog-async = "2"
slog-perf = "0.2"
slog-term = "2"
time = "0.2"
tokio = "0.1"
tokio-threadpool = "0.1"
trust-dns-proto = "0.7"
trust-dns-resolver = "0.11"
ts-bookkeeping = { path = "../utils/ts-bookkeeping" }
tsproto = { path = "../tsproto", version = "=0.1.0" }
tsproto-packets = { path = "../utils/tsproto-packets" }

[build-dependencies]
heck = "0.3"
t4rust-derive = "0.1.3"
tsproto-structs = { path = "../utils/tsproto-structs", version = "=0.1.0" }

[dev-dependencies]
audiopus = "0.1"
sdl2 = "0.32"
structopt = { version = "0.3", default-features = false }
tokio-signal = "0.2"
