[workspace]
members = [
	"tsclientlib",
	"tsclientlib-ffi",
	"tsproto",
	"utils/analyzer",
	"utils/cli-completer",
	"utils/gst-plugin-ts3",
	"utils/tsproto-audio",
	"utils/tsproto-commands",
	"utils/tsproto-structs",
	"utils/tsproto-util",
]
