[package]
name = "tsproto-packets"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
license = "OSL-3.0"
edition = "2018"

[dependencies]
arrayref = "0.3"
base64 = "0.10"
bitflags = "1"
byteorder = "1"
bytes = "0.4"
derive_more = "0.14"
failure = "0.1"
nom = "4"
num-derive = "0.2"
num-traits = "0.2"
rental = "0.5"
stable_deref_trait = "1"
