[package]
name = "ffigen-derive"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ffigen = { path = "../ffigen" }
quote = "0.6"
syn = "0.15"
proc-macro2 = "0.4"
