[package]
name = "analyzer"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]

[dependencies]
failure = "0.1"
num-traits = "0.2"
pcap = "0.7"
pnet_packet = "0.21"
structopt = "0.2"
structopt-derive = "0.2"
tsproto = { path = "../tsproto" }
