[package]
name = "tsproto-commands"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
build = "build/build.rs"

[dependencies]
chrono = "0.4"
tsproto = { path = "../tsproto" }
num = "0.1"
num-derive = "0.1"

[build-dependencies]
csv = "1.0.0-beta.5"
t4rust-derive = { git = "https://github.com/ReSpeak/t4rust.git" }
serde = "1"
serde_derive = "1"
