[package]
name = "tsproto-commands"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
build = "build/build.rs"

[dependencies]
chrono = "0.4"
futures = "0.1"
num = "0.1"
num-derive = "0.1"
slog = "2"
tsproto = { path = "../tsproto" }

[build-dependencies]
tsproto-util = { path = "../tsproto-util" }