[package]
name = "tsproto-types"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
description = "Basic types for TeamSpeak"
license = "OSL-3.0"
repository = "https://github.com/ReSpeak/tsclientlib"
keywords = ["TeamSpeak3", "TS3"]
build = "build/build.rs"
edition = "2018"

[dependencies]
arrayref = "0.3"
base64 = "0.11"
bitflags = "1"
curve25519-dalek = "2"
flakebi-ring = "0.16.9"
num-bigint = "0.2"
num-traits = "0.2"
num-derive = "0.3"
rand = "0.7"
serde = { version = "1", features = ["derive"] }
simple_asn1 = "0.4"
thiserror = "1"
time = { version = "0.2", features = ["serde"] }
untrusted = "0.7"

[build-dependencies]
heck = "0.3"
itertools = "0.8"
t4rust-derive = "0.2"
tsproto-structs = { path = "../tsproto-structs", version = "=0.1.0" }
