[package]
name = "ts-bookkeeping"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
license = "OSL-3.0"
edition = "2018"
build = "build/build.rs"

[dependencies]
base64 = "0.10"
derive_more = "0.14"
failure = "0.1"
num-traits = "0.2"
num-derive = "0.2"
serde = { version = "1", features = ["derive"] }
time = { version = "0.2", features = ["serde"] }
tsproto-packets = { path = "../tsproto-packets" }
tsproto-types = { path = "../tsproto-types" }

[build-dependencies]
heck = "0.3"
itertools = "0.8"
t4rust-derive = "0.1.3"
tsproto-structs = { path = "../tsproto-structs", version = "=0.1.0" }
