[package]
name = "tsproto"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
description = """
An implementation of the TeamSpeak3 protocol as a library for use in clients and bots.
"""
repository = "https://github.com/ReSpeak/tsclientlib"
keywords = ["teamspeak3", "ts3", "voip"]
categories = ["multimedia"]
license = "MIT/Apache-2.0"
build = "build/build.rs"
autobenches = false

[badges]
travis-ci = { repository = "ReSpeak/tsclientlib" }

[features]
default = ["rug"]

[dependencies]
arrayref = "0.3"
#simple_asn1 = "0.2"
simple_asn1 = { git = "https://github.com/Flakebi/simple_asn1.git" }
base64 = "0.10"
bitflags = "1"
byteorder = "1"
bytes = "0.4"
chrono = "0.4"
curve25519-dalek = "0.21"
derive_more = "0.13"
failure = "0.1"
futures = "0.1"
nom = "4"
num-bigint = "0.2"
num-derive = "0.2"
num-traits = "0.2"
openssl = "0.10"
parking_lot = "0.7"
rand = "0.6"
rental = "0.5"
ring = "0.13"
rug = { version = "1", optional = true }
slog-async = "2"
slog-perf = "0.2"
slog-term = "2"
stable_deref_trait = "1"
tokio = "0.1"
tokio-threadpool = "0.1"
quicklz = "0.2"

[dependencies.slog]
version = "2"
features = ["max_level_debug", "release_max_level_debug"]

[build-dependencies]
tsproto-util = { path = "../tsproto-util" }

[dev-dependencies]
#cpuprofiler = "0.0.3"
criterion = "0.2"
#glib = "0.5"
#gstreamer = { version = "0.11", features = ["futures"] }
#gstreamer-app = "0.11"
#gstreamer-audio = "0.11"
structopt = "0.2"
tokio-signal = "0.2"

[[bench]]
name = "modpow"
harness = false

[[bench]]
name = "command"
harness = false

[[bench]]
name = "connect"
harness = false

[[bench]]
name = "message"
harness = false
