[package]
name = "tsproto"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
description = """
An implementation of the TeamSpeak3 protocol as a library for use in clients and bots.
"""
repository = "https://github.com/ReSpeak/tsclientlib"
documentation = "https://docs.rs/tsproto"
keywords = ["teamspeak3", "ts3", "voip"]
categories = ["multimedia"]
license = "MIT/Apache-2.0"
build = "build/build.rs"

[badges]
travis-ci = { repository = "ReSpeak/tsclientlib" }

[features]
default = ["rust-gmp"]

[dependencies]
base64 = "0.9"
byteorder = "1"
chrono = "0.4"
curve25519-dalek = "0.15"
failure = "0.1"
futures = "0.1"
nom = "3.2"
num = "0.1"
num-derive = "0.2"
num-traits = "0.2"
openssl = { git = "https://github.com/Flakebi/rust-openssl.git" }
rand = "0.4"
ring = "0.13.0-alpha"
rust-gmp = { version = "0.5", optional = true }
slog-async = "2"
slog-perf = "0.2"
slog-term = "2"
tokio-core = "0.1"
#quicklz = "0.1"
quicklz = { git = "https://github.com/ReSpeak/quicklz.git" }
yasna = "0.1"

[dependencies.slog]
version = "2"
features = ["max_level_debug", "release_max_level_debug"]

[dev-dependencies]
cpuprofiler = "0.0.3"
structopt = "0.2"
structopt-derive = "0.2"
