[package]
name = "tsproto-util"
version = "0.1.0"
authors = ["Splamy <splamyn@gmail.com>"]

[dependencies]
t4rust-derive = { git = "https://github.com/ReSpeak/t4rust.git" }
tsproto-structs = { git = "https://github.com/ReSpeak/ts-dev-tools.git" }
