[package]
name = "tsproto-bookkeeping"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
build = "build/build.rs"

[dependencies]
tsproto = { path = "../tsproto" }

[build-dependencies]
regex = "0.2"
t4rust-derive = { git = "https://github.com/ReSpeak/t4rust.git" }
