[package]
name = "tsclientlib-ffi"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
chashmap = "2"
failure = "0.1"
lazy_static = "1"
tokio = "0.1"
tsclientlib = { path = "../tsclientlib" }
